export DATA_TYPE=real
export DATA_FILENAME=asia
export DATA_DIR=BIFs
export DATA_SAMPLE_SIZE=5000 #n
export DATA_VARIABLE_SIZE=10 
export GRAPH_TYPE=erdos-renyi 
export GRAPH_DEGREE=2 
export GRAPH_SEM_TYPE=linear-gauss #sem_type
export GRAPH_LINEAR_TYPE=nonlinear_2 #linear_type
export EDGE_TYPES=2
export X_DIMS=1 #x_dims
export Z_DIMS=1

export OPTIMIZER=Adam
export GRAPH_THRESHOLD=0.3
export TAU_A=0.0
export LAMBDA_A=0.0
export C_A=1
export USE_A_CONNECT_LOSS=0
export USE_A_POSITIVER_LOSS=0

export NO_CUDA=True
export SEED=42
export EPOCHS=300
export BATCH_SIZE=100
export LR=3e-3
export ENCODER_HIDDEN=64
export DECODER_HIDDEN=64
export TEMP=0.5
export K_MAX_ITER=5

export ENCODER=mlp
export DECODER=mlp
export NO_FACTOR=False
export SUFFIX=_springs5
export ENCODER_DROPOUT=0.0
export DECODER_DROPOUT=0.0
export SAVE_FOLDER=logs
export LOAD_FOLDER=

export H_TOL=1e-8
export PREDICTION_STEPS=10
export LR_DECAY=200
export GAMMA=1.0
export SKIP_FIRST=False
export VAR=5e-5
export HARD=False
export PRIOR=False
export DYNAMIC_GRAPH=False

python src/train.py \
--data_type=$DATA_TYPE \
--data_filename=$DATA_FILENAME \
--data_dir=$DATA_DIR \
--data_sample_size=$DATA_SAMPLE_SIZE \
--data_variable_size=$DATA_VARIABLE_SIZE \
--graph_type=$GRAPH_TYPE \
--graph_degree=$GRAPH_DEGREE \
--graph_sem_type=$GRAPH_SEM_TYPE \
--graph_linear_type=$GRAPH_LINEAR_TYPE \
--edge_types=$EDGE_TYPES \
--x_dims=$X_DIMS \
--z_dims=$Z_DIMS \
--optimizer=$OPTIMIZER \
--graph_threshold=$GRAPH_THRESHOLD \
--tau_A=$TAU_A \
--lambda_A=$LAMBDA_A \
--c_A=$C_A \
--use_A_connect_loss=$USE_A_CONNECT_LOSS \
--use_A_positiver_loss=$USE_A_POSITIVER_LOSS \
--no_cuda=$NO_CUDA \
--seed=$SEED \
--epochs=$EPOCHS \
--batch_size=$BATCH_SIZE \
--lr=$LR \
--encoder_hidden=$ENCODER_HIDDEN \
--decoder_hidden=$DECODER_HIDDEN \
--temp=$TEMP \
--k_max_iter=$K_MAX_ITER \
--encoder=$ENCODER \
--decoder=$DECODER \
--no_factor=$NO_FACTOR \
--suffix=$SUFFIX \
--encoder_dropout=$ENCODER_DROPOUT \
--decoder_dropout=$DECODER_DROPOUT \
--save_folder=$SAVE_FOLDER \
--load_folder=$LOAD_FOLDER \
--h_tol=$H_TOL \
--prediction_steps=$PREDICTION_STEPS \
--lr_decay=$LR_DECAY \
--gamma=$GAMMA \
--skip_first=$SKIP_FIRST \
--var=$VAR \
--hard=$HARD \
--prior=$PRIOR \
--dynamic_graph=$DYNAMIC_GRAPH